// ==================== MOCK DATA ====================
const MOCK = {
  currentUser: {
    id: 'RV-00124', firstName: 'Ahmed', lastName: 'Mohamed', fullName: 'Ahmed Mohamed',
    email: 'ahmed.mohamed@revive.com', phone: '+20 101 234 5678', initials: 'AM',
    position: 'Trainer', level: 'Senior',
    gym: { id: 'gym-1', name: 'Revive Gym', branch: 'Nasr City' },
    hireDate: '2026-01-12', employmentType: 'Full-time', status: 'Active',
    role: 'Branch Manager',
    permissions: ['team_view','team_requests_approve','team_attendance','team_schedule','team_followup','recruitment_request','employee_leaving'],
    dateOfBirth: '1995-03-15', nationalId: '29503151234567', gender: 'Male',
    address: '15 El-Thawra St, Nasr City, Cairo',
    emergencyContact: { name: 'Mohamed Ahmed', relationship: 'Father', phone: '+20 100 987 6543' },
    baseSalary: 12000,
  },
  todayShift: { shiftName: 'Morning', startTime: '08:00', endTime: '16:00', gym: 'Revive Gym', status: 'Published' },
  todayAttendance: { scheduledStart: '08:00', checkIn: '08:02', checkOut: null, status: 'On Time', checkedIn: true, source: 'Biometric Device' },
  attendanceSummary: { rate: 96.4, present: 22, late: 2, absent: 1, earlyCheckout: 1, missingCheckout: 0 },
  attendanceRecords: [
    { date: '2026-08-26', shift: '08:00–16:00', shiftName: 'Morning', checkIn: '08:02', checkOut: null, status: 'On Time', source: 'Biometric Device', notes: '' },
    { date: '2026-08-25', shift: '16:00–00:00', shiftName: 'Evening', checkIn: '16:08', checkOut: '00:01', status: 'Late', source: 'Biometric Device', notes: 'Traffic delay' },
    { date: '2026-08-24', shift: 'OFF', shiftName: 'Off', checkIn: null, checkOut: null, status: 'Off', source: '', notes: '' },
    { date: '2026-08-23', shift: '08:00–16:00', shiftName: 'Morning', checkIn: '07:58', checkOut: '16:03', status: 'On Time', source: 'Biometric Device', notes: '' },
    { date: '2026-08-22', shift: '08:00–16:00', shiftName: 'Morning', checkIn: '08:00', checkOut: '15:30', status: 'Early Checkout', source: 'Biometric Device', notes: 'Approved early leave' },
    { date: '2026-08-21', shift: '16:00–00:00', shiftName: 'Evening', checkIn: '16:02', checkOut: '00:05', status: 'On Time', source: 'Biometric Device', notes: '' },
    { date: '2026-08-20', shift: 'OFF', shiftName: 'Off', checkIn: null, checkOut: null, status: 'Off', source: '', notes: '' },
    { date: '2026-08-19', shift: '08:00–16:00', shiftName: 'Morning', checkIn: '08:30', checkOut: '16:00', status: 'Late', source: 'Manual', notes: 'Medical appointment' },
    { date: '2026-08-18', shift: '16:00–00:00', shiftName: 'Evening', checkIn: '15:58', checkOut: '00:02', status: 'On Time', source: 'Biometric Device', notes: '' },
    { date: '2026-08-17', shift: '08:00–16:00', shiftName: 'Morning', checkIn: null, checkOut: null, status: 'Absent', source: '', notes: 'No show' },
  ],
  scheduleCycles: [
    { id: 'c1', label: 'Aug 4 – Aug 13', status: 'Published' },
    { id: 'c2', label: 'Aug 14 – Aug 23', status: 'Published' },
    { id: 'c3', label: 'Aug 24 – Sep 2', status: 'Published' },
  ],
  shiftTemplates: [
    { id: 'st-morning', name: 'Morning', start: '08:00', end: '16:00', color: '#2563eb', bgColor: '#dbeafe', textColor: '#1e40af', isOff: false },
    { id: 'st-evening', name: 'Evening', start: '16:00', end: '00:00', color: '#16a34a', bgColor: '#dcfce7', textColor: '#166534', isOff: false },
    { id: 'st-night', name: 'Night', start: '00:00', end: '08:00', color: '#7c3aed', bgColor: '#ede9fe', textColor: '#5b21b6', isOff: false },
    { id: 'st-off', name: 'Off Day', start: null, end: null, color: '#6b7280', bgColor: '#f3f4f6', textColor: '#6b7280', isOff: true },
  ],
  scheduleData: {
    'c3': [
      { date: '2026-08-24', day: 'SUN', dayNum: 24, shiftName: 'Morning', start: '08:00', end: '16:00', isOff: false },
      { date: '2026-08-25', day: 'MON', dayNum: 25, shiftName: 'Evening', start: '16:00', end: '00:00', isOff: false },
      { date: '2026-08-26', day: 'TUE', dayNum: 26, shiftName: 'Morning', start: '08:00', end: '16:00', isOff: false, isToday: true },
      { date: '2026-08-27', day: 'WED', dayNum: 27, shiftName: 'Off', start: null, end: null, isOff: true },
      { date: '2026-08-28', day: 'THU', dayNum: 28, shiftName: 'Morning', start: '08:00', end: '16:00', isOff: false },
      { date: '2026-08-29', day: 'FRI', dayNum: 29, shiftName: 'Evening', start: '16:00', end: '00:00', isOff: false },
      { date: '2026-08-30', day: 'SAT', dayNum: 30, shiftName: 'Morning', start: '08:00', end: '16:00', isOff: false },
      { date: '2026-08-31', day: 'SUN', dayNum: 31, shiftName: 'Off', start: null, end: null, isOff: true },
      { date: '2026-09-01', day: 'MON', dayNum: 1, shiftName: 'Evening', start: '16:00', end: '00:00', isOff: false },
      { date: '2026-09-02', day: 'TUE', dayNum: 2, shiftName: 'Morning', start: '08:00', end: '16:00', isOff: false },
    ]
  },
  teamSchedule: {
    't1': ['st-morning','st-evening','st-off','st-morning','st-evening','st-morning','st-off'],
    't2': ['st-morning','st-morning','st-evening','st-off','st-morning','st-morning','st-off'],
    't3': ['st-evening','st-off','st-morning','st-morning','st-evening','st-off','st-morning'],
    't4': ['st-morning','st-morning','st-morning','st-morning','st-morning','st-off','st-off'],
    't5': ['st-off','st-morning','st-evening','st-evening','st-off','st-morning','st-morning'],
    't6': ['st-evening','st-evening','st-off','st-morning','st-evening','st-evening','st-off'],
    't7': ['st-morning','st-off','st-morning','st-evening','st-morning','st-off','st-evening'],
    't8': ['st-morning','st-morning','st-off','st-morning','st-off','st-morning','st-morning'],
    't9': ['st-evening','st-morning','st-off','st-evening','st-evening','st-morning','st-off'],
    't10': ['st-morning','st-evening','st-morning','st-off','st-morning','st-evening','st-morning'],
  },
  currentCycleIndex: 2,
  payroll: [
    { id: 'p1', period: 'August 2026', status: 'Processing', paidDate: null, netSalary: null, visible: false,
      items: [], grossEarnings: 0, totalDeductions: 0 },
    { id: 'p2', period: 'July 2026', status: 'Paid', paidDate: '2026-08-05', netSalary: 11200, visible: true,
      baseSalary: 12000, workingDays: 26, workedDays: 24,
      items: [
        { label: 'Base Salary', amount: 12000, type: 'earning', icon: 'payments', color: 'brand' },
        { label: 'Performance Bonus', amount: 500, type: 'earning', icon: 'star', color: 'yellow' },
        { label: 'Overtime Pay', amount: 200, type: 'earning', icon: 'schedule', color: 'blue' },
        { label: 'Social Insurance (7%)', amount: -840, type: 'deduction', icon: 'health_and_safety', color: 'red' },
        { label: 'Tax', amount: -480, type: 'deduction', icon: 'receipt_long', color: 'red' },
        { label: 'Attendance Deductions', amount: -180, type: 'deduction', icon: 'event_busy', color: 'orange', isGroup: true,
          subItems: [
            { label: 'Late Arrival — Jul 5', amount: -60, date: '2026-07-05', detail: '15 min late (08:15 check-in)', icon: 'alarm_off' },
            { label: 'Late Arrival — Jul 12', amount: -60, date: '2026-07-12', detail: '22 min late (08:22 check-in)', icon: 'alarm_off' },
            { label: 'Day Off (Unapproved) — Jul 18', amount: -60, date: '2026-07-18', detail: 'Absent without approval', icon: 'event_busy' },
          ]
        },
      ], grossEarnings: 12700, totalDeductions: 1500 },
    { id: 'p3', period: 'June 2026', status: 'Paid', paidDate: '2026-07-05', netSalary: 11500, visible: true,
      baseSalary: 12000, workingDays: 26, workedDays: 25,
      items: [
        { label: 'Base Salary', amount: 12000, type: 'earning', icon: 'payments', color: 'brand' },
        { label: 'Performance Bonus', amount: 800, type: 'earning', icon: 'star', color: 'yellow' },
        { label: 'Social Insurance (7%)', amount: -840, type: 'deduction', icon: 'health_and_safety', color: 'red' },
        { label: 'Tax', amount: -460, type: 'deduction', icon: 'receipt_long', color: 'red' },
      ], grossEarnings: 12800, totalDeductions: 1300 },
    { id: 'p4', period: 'May 2026', status: 'Paid', paidDate: '2026-06-05', netSalary: 11000, visible: true,
      baseSalary: 12000, workingDays: 27, workedDays: 25,
      items: [
        { label: 'Base Salary', amount: 12000, type: 'earning', icon: 'payments', color: 'brand' },
        { label: 'Social Insurance (7%)', amount: -840, type: 'deduction', icon: 'health_and_safety', color: 'red' },
        { label: 'Tax', amount: -160, type: 'deduction', icon: 'receipt_long', color: 'red' },
      ], grossEarnings: 12000, totalDeductions: 1000 },
  ],
  documents: [
    { id: 'd1', name: 'Employment Contract', category: 'Employment', uploadDate: '2026-01-12', expiryDate: null, status: 'Valid', canDownload: true },
    { id: 'd2', name: 'National ID (Front & Back)', category: 'Identification', uploadDate: '2026-01-12', expiryDate: '2031-03-15', status: 'Valid', canDownload: true },
    { id: 'd3', name: 'Personal Photo', category: 'Identification', uploadDate: '2026-01-12', expiryDate: null, status: 'Valid', canDownload: true },
    { id: 'd4', name: 'First Aid Certification', category: 'Certification', uploadDate: '2026-02-20', expiryDate: '2026-09-10', status: 'Expiring Soon', canDownload: true },
    { id: 'd5', name: 'Personal Training Certificate', category: 'Certification', uploadDate: '2026-02-20', expiryDate: '2028-02-20', status: 'Valid', canDownload: true },
    { id: 'd6', name: 'Medical Fitness Certificate', category: 'Medical', uploadDate: '2026-01-10', expiryDate: '2027-01-10', status: 'Valid', canDownload: true },
    { id: 'd7', name: 'Bank Account Details', category: 'Financial', uploadDate: '2026-01-15', expiryDate: null, status: 'Valid', canDownload: false },
    { id: 'd8', name: 'Degree Certificate', category: 'Education', uploadDate: '2026-01-12', expiryDate: null, status: 'Valid', canDownload: true },
  ],
  employmentHistory: [
    { month: 'AUGUST 2026', events: [
      { type: 'Position Changed', icon: 'briefcase', from: 'Junior Trainer', to: 'Trainer', effective: '01 Aug 2026', detail: 'Promoted based on Q2 2026 evaluation performance.' }
    ]},
    { month: 'MAY 2026', events: [
      { type: 'Gym Transfer', icon: 'building', from: 'Revive Gym — Heliopolis', to: 'Revive Gym — Nasr City', effective: '01 May 2026', detail: 'Requested transfer approved by HR.' }
    ]},
    { month: 'FEBRUARY 2026', events: [
      { type: 'Role Added', icon: 'shield', from: 'Employee', to: 'Employee + Branch Manager', effective: '15 Feb 2026', detail: 'Assigned Branch Manager responsibilities for Nasr City.' }
    ]},
    { month: 'JANUARY 2026', events: [
      { type: 'Joined Revive', icon: 'star', from: null, to: null, effective: '12 Jan 2026', detail: 'Initial hire as Junior Trainer at Revive Gym — Heliopolis.',
        extra: [{ label: 'Gym', value: 'Revive Gym — Heliopolis' },{ label: 'Position', value: 'Junior Trainer' },{ label: 'Type', value: 'Full-time' },{ label: 'Contract', value: '1 Year Fixed Term' }]
      }
    ]},
  ],
  evaluations: [
    { id: 'e1', period: 'Q3 2026', score: 4.2, maxScore: 5, status: 'Completed', date: '2026-08-01', reviewer: 'Sarah Hassan',
      criteria: [
        { name: 'Customer Service', score: 4.5, comment: 'Excellent member engagement and feedback scores.' },
        { name: 'Team Collaboration', score: 4.0, comment: 'Works well with colleagues, actively helps new team members.' },
        { name: 'Punctuality & Attendance', score: 3.8, comment: 'Generally on time; one late arrival noted.' },
        { name: 'Technical Skills', score: 4.3, comment: 'Strong training knowledge, updated certifications.' },
        { name: 'Initiative', score: 4.2, comment: 'Proposed new class format that was well received.' },
      ],
      overallComment: 'Ahmed has shown consistent improvement this quarter. His initiative in developing new training programs has been commendable.'
    },
    { id: 'e2', period: 'Q2 2026', score: 3.8, maxScore: 5, status: 'Completed', date: '2026-05-01', reviewer: 'Sarah Hassan',
      criteria: [
        { name: 'Customer Service', score: 4.0, comment: 'Good member satisfaction scores.' },
        { name: 'Team Collaboration', score: 3.5, comment: 'Works adequately in team settings.' },
        { name: 'Punctuality & Attendance', score: 3.5, comment: 'Two late arrivals this quarter.' },
        { name: 'Technical Skills', score: 4.0, comment: 'Solid training fundamentals.' },
        { name: 'Initiative', score: 4.0, comment: 'Showed improvement in taking ownership.' },
      ],
      overallComment: 'Good performance overall. Areas for improvement in punctuality and deeper team engagement.'
    },
    { id: 'e3', period: 'Q1 2026', score: 3.5, maxScore: 5, status: 'Completed', date: '2026-02-01', reviewer: 'Sarah Hassan',
      criteria: [
        { name: 'Customer Service', score: 3.5, comment: 'Adequate service, room for improvement.' },
        { name: 'Team Collaboration', score: 3.0, comment: 'New to team, still building relationships.' },
        { name: 'Punctuality & Attendance', score: 4.0, comment: 'Good attendance record as a new hire.' },
        { name: 'Technical Skills', score: 3.5, comment: 'Solid foundation, needs experience.' },
        { name: 'Initiative', score: 3.5, comment: 'Shows willingness to learn.' },
      ],
      overallComment: 'First quarter as a new hire. Ahmed is settling in well and showing promise.'
    },
  ],
  requests: [
    { id: 'r1', type: 'Day Off', submittedDate: '2026-08-26', requestedDate: 'Aug 29, 2026', status: 'Pending',
      reason: "Family event — cousin's wedding", reviewer: 'Pending Review', reviewerComment: '',
      timeline: [{ step: 'Submitted', date: 'Aug 26, 09:42 AM', done: true },{ step: 'Under Review', date: 'Pending', done: false },{ step: 'Approved', date: '', done: false }],
      scheduleContext: 'Scheduled: Morning Shift (08:00–16:00)' },
    { id: 'r2', type: 'Leave Early', submittedDate: '2026-08-20', requestedDate: 'Aug 22, 2026', status: 'Approved',
      reason: 'Medical appointment at 3:00 PM', reviewer: 'Sarah Hassan (Branch Manager)',
      reviewerComment: 'Approved. Please ensure handover to Karim before leaving.',
      timeline: [{ step: 'Submitted', date: 'Aug 20, 11:15 AM', done: true },{ step: 'Under Review', date: 'Aug 20, 02:30 PM', done: true },{ step: 'Approved', date: 'Aug 20, 03:00 PM', done: true }],
      scheduleContext: 'Scheduled: Morning Shift (08:00–16:00)' },
    { id: 'r3', type: 'Day Off', submittedDate: '2026-08-10', requestedDate: 'Aug 15, 2026', status: 'Rejected',
      reason: 'Personal day', reviewer: 'Sarah Hassan (Branch Manager)',
      reviewerComment: 'Rejected — high staff shortage on Aug 15. Please reschedule.',
      timeline: [{ step: 'Submitted', date: 'Aug 10, 08:20 AM', done: true },{ step: 'Under Review', date: 'Aug 10, 10:00 AM', done: true },{ step: 'Rejected', date: 'Aug 10, 01:15 PM', done: true }],
      scheduleContext: 'Scheduled: Morning Shift (08:00–16:00)' },
    { id: 'r4', type: 'Shift Swap', submittedDate: '2026-08-05', requestedDate: 'Aug 10, 2026', status: 'Approved',
      reason: "Need to swap Aug 10 morning shift with Karim's evening shift", reviewer: 'Sarah Hassan (Branch Manager)',
      reviewerComment: 'Approved. Karim has agreed to the swap.',
      timeline: [{ step: 'Submitted', date: 'Aug 05, 04:10 PM', done: true },{ step: 'Under Review', date: 'Aug 06, 09:00 AM', done: true },{ step: 'Approved', date: 'Aug 06, 11:30 AM', done: true }],
      scheduleContext: null },
    { id: 'r5', type: 'Document Request', submittedDate: '2026-07-28', requestedDate: 'Jul 28, 2026', status: 'Approved',
      reason: 'Requesting copy of employment contract for personal records', reviewer: 'HR Department',
      reviewerComment: 'Document uploaded to your Documents section.',
      timeline: [{ step: 'Submitted', date: 'Jul 28, 10:00 AM', done: true },{ step: 'Under Review', date: 'Jul 28, 02:00 PM', done: true },{ step: 'Approved', date: 'Jul 29, 09:00 AM', done: true }],
      scheduleContext: null },
  ],
  requestTypes: [
    { id: 'day-off', label: 'Day Off', fields: ['date','reason'] },
    { id: 'leave-early', label: 'Leave Early', fields: ['date','time','reason'] },
    { id: 'late-arrival', label: 'Late Arrival', fields: ['date','time','reason'] },
    { id: 'shift-swap', label: 'Shift Swap', fields: ['date-from','date-to','colleague','reason'] },
    { id: 'overtime', label: 'Overtime Request', fields: ['date','time-from','time-to','reason'] },
    { id: 'document-request', label: 'Document Request', fields: ['document-type','reason'] },
    { id: 'correction', label: 'Attendance Correction', fields: ['date','correction-type','reason'] },
  ],
  notifications: [
    { id: 'n1', category: 'Requests', title: 'Request Approved', description: 'Your Leave Early request for Aug 22 has been approved.', date: '2026-08-20 15:00', read: true, color: 'green', link: 'requests' },
    { id: 'n2', category: 'Schedule', title: 'Schedule Updated', description: 'Your schedule for Aug 24 – Sep 2 has been published.', date: '2026-08-22 10:00', read: false, color: 'blue', link: 'schedule' },
    { id: 'n3', category: 'Payroll', title: 'Payslip Available', description: 'Your July 2026 payslip is now available for download.', date: '2026-08-05 09:00', read: false, color: 'green', link: 'payroll' },
    { id: 'n4', category: 'Documents', title: 'Document Expiring Soon', description: 'Your First Aid Certification expires on Sep 10, 2026.', date: '2026-08-24 08:00', read: false, color: 'orange', link: 'documents' },
    { id: 'n5', category: 'Evaluations', title: 'Q3 2026 Evaluation Complete', description: 'Your performance evaluation for Q3 2026 is now available.', date: '2026-08-01 14:00', read: true, color: 'purple', link: 'evaluations' },
    { id: 'n6', category: 'HR Announcements', title: 'Updated Gym Policy', description: 'Please review the updated attendance policy effective Sep 1.', date: '2026-08-25 11:00', read: false, color: 'blue', link: null },
    { id: 'n7', category: 'Requests', title: 'Request Rejected', description: 'Your Day Off request for Aug 15 was rejected.', date: '2026-08-10 13:15', read: true, color: 'red', link: 'requests' },
    { id: 'n8', category: 'System', title: 'Password Expiry Warning', description: 'Your password will expire in 15 days.', date: '2026-08-26 08:00', read: false, color: 'yellow', link: 'settings' },
  ],
  teamMembers: [
    { id: 't1', name: 'Karim Hassan', position: 'Trainer', status: 'Present', checkIn: '07:58', initials: 'KH' },
    { id: 't2', name: 'Sara Ali', position: 'Receptionist', status: 'Present', checkIn: '07:55', initials: 'SA' },
    { id: 't3', name: 'Omar Youssef', position: 'Trainer', status: 'Late', checkIn: '08:15', initials: 'OY' },
    { id: 't4', name: 'Nour Ibrahim', position: 'Cleaner', status: 'Present', checkIn: '06:00', initials: 'NI' },
    { id: 't5', name: 'Yasmin Adel', position: 'Trainer', status: 'Absent', checkIn: null, initials: 'YA' },
    { id: 't6', name: 'Tarek Nabil', position: 'Receptionist', status: 'Present', checkIn: '15:52', initials: 'TN' },
    { id: 't7', name: 'Mona Said', position: 'Trainer', status: 'Present', checkIn: '07:50', initials: 'MS' },
    { id: 't8', name: 'Hassan Ali', position: 'Maintenance', status: 'Present', checkIn: '08:00', initials: 'HA' },
    { id: 't9', name: 'Fatma Hassan', position: 'Trainer', status: 'Late', checkIn: '08:20', initials: 'FH' },
    { id: 't10', name: 'Ahmed Zaki', position: 'Trainer', status: 'Present', checkIn: '07:45', initials: 'AZ' },
  ],
  teamStats: { total: 42, present: 38, late: 3, absent: 1, pendingRequests: 7, upcomingIssues: 4 },
  teamRequests: [
    { id: 'tr1', employee: 'Karim Hassan', type: 'Day Off', date: 'Aug 30, 2026', submitted: 'Aug 25', status: 'Pending' },
    { id: 'tr2', employee: 'Sara Ali', type: 'Late Arrival', date: 'Aug 27, 2026', submitted: 'Aug 26', status: 'Pending' },
    { id: 'tr3', employee: 'Nour Ibrahim', type: 'Day Off', date: 'Sep 1, 2026', submitted: 'Aug 24', status: 'Pending' },
    { id: 'tr4', employee: 'Omar Youssef', type: 'Leave Early', date: 'Aug 28, 2026', submitted: 'Aug 23', status: 'Approved' },
    { id: 'tr5', employee: 'Yasmin Adel', type: 'Shift Swap', date: 'Aug 29-30', submitted: 'Aug 22', status: 'Pending' },
    { id: 'tr6', employee: 'Mona Said', type: 'Day Off', date: 'Sep 5, 2026', submitted: 'Aug 21', status: 'Rejected' },
    { id: 'tr7', employee: 'Fatma Hassan', type: 'Overtime', date: 'Aug 26, 2026', submitted: 'Aug 20', status: 'Pending' },
  ],
  followUpItems: [
    { id: 'f1', employee: 'Yasmin Adel', type: 'Absent', description: 'Absent today without prior notice', severity: 'high' },
    { id: 'f2', employee: 'Omar Youssef', type: 'Late Pattern', description: '3rd late arrival this month', severity: 'medium' },
    { id: 'f3', employee: 'Fatma Hassan', type: 'Document Expiring', description: 'PT Certificate expires in 15 days', severity: 'low' },
    { id: 'f4', employee: 'Tarek Nabil', type: 'Performance', description: 'Q2 evaluation below expectations', severity: 'medium' },
  ],
  recruitmentRequests: [
    { id: 'rr1', position: 'Senior Trainer', count: 1, urgency: 'High', status: 'Approved', date: 'Aug 20, 2026' },
    { id: 'rr2', position: 'Receptionist', count: 1, urgency: 'Medium', status: 'Pending', date: 'Aug 15, 2026' },
    { id: 'rr3', position: 'Cleaner', count: 2, urgency: 'Low', status: 'Submitted', date: 'Aug 10, 2026' },
  ],
  employeeLeaving: [
    { id: 'el1', employee: 'Mona Said', position: 'Trainer', lastDay: 'Sep 30, 2026', status: 'Notice Period', reason: 'Personal reasons' },
  ],
  settings: {
    emailNotifications: true,
    pushNotifications: true,
    scheduleNotifications: true,
    attendanceNotifications: true,
    payrollNotifications: true,
    requestNotifications: false,
  },
};