// ==================== HR MOCK DATA ====================
const MOCK = {
  currentUser: {
    id: 'RV-00102', firstName: 'Mona', lastName: 'El-Sayed', fullName: 'Mona El-Sayed',
    email: 'mona.elsayed@revive.com', phone: '+20 103 456 7890', initials: 'ME',
    position: 'HR Manager', level: 'Manager',
    gyms: [
      { id: 'gym-1', name: 'Revive Gym', branch: 'Nasr City' },
      { id: 'gym-2', name: 'Revive Gym', branch: 'Heliopolis' },
      { id: 'gym-3', name: 'Revive Fitness', branch: '6th October' },
    ],
    selectedGym: 'all',
    hireDate: '2024-03-15', employmentType: 'Full-time', status: 'Active',
    role: 'HR Manager',
    permissions: ['employees.view','employees.create','employees.edit','employees.transfer','employees.position.change','employees.role.assign','employees.status.change','employees.compensation.manage','employees.contract.manage','employees.offboard','employees.documents.view','employees.documents.manage','employees.bulk_import','employees.leave_balance.manage','positions.view','positions.manage','attendance.view','attendance.edit','attendance.manual_entry','schedule.view','schedule.manage','requests.view','requests.approve','payroll.view','payroll.edit','payroll.approve','evaluations.view','evaluations.manage','reports.view','announcements.view','announcements.manage','audit.view','team.view','team.manage','recruitment.view','recruitment.vacancies.manage','recruitment.candidates.manage','recruitment.hire.approve','recruitment.vacancy_request.approve'],
    dateOfBirth: '1988-07-08', nationalId: '28807081234567', gender: 'Female',
    address: '22 Abbas El-Akkad St, Nasr City, Cairo',
    emergencyContact: { name: 'El-Sayed Mahmoud', relationship: 'Father', phone: '+20 100 333 4444' },
  },
  dashboardStats: { totalEmployees: 142, pendingRequests: 18, openVacancies: 7, todayAttendance: 91, shiftCyclesActive: 2, overdueEvaluations: 4 },
  gymList: [
    { id: 'gym-1', name: 'Revive Gym', branch: 'Nasr City', employees: 58 },
    { id: 'gym-2', name: 'Revive Gym', branch: 'Heliopolis', employees: 45 },
    { id: 'gym-3', name: 'Revive Fitness', branch: '6th October', employees: 39 },
  ],
  employees: [
    { id: 'RV-00124', name: 'Ahmed Mohamed', position: 'Trainer', level: 'Senior', gym: 'Nasr City', status: 'Active', initials: 'AM', hireDate: '2026-01-12', salary: 12000, phone: '+20 101 234 5678', email: 'ahmed.mohamed@revive.com' },
    { id: 'RV-00125', name: 'Karim Hassan', position: 'Trainer', level: 'Mid', gym: 'Nasr City', status: 'Active', initials: 'KH', hireDate: '2025-08-15', salary: 10000, phone: '+20 101 345 6789', email: 'karim.hassan@revive.com' },
    { id: 'RV-00126', name: 'Sara Ali', position: 'Receptionist', level: 'Junior', gym: 'Nasr City', status: 'Active', initials: 'SA', hireDate: '2026-03-01', salary: 7000, phone: '+20 102 456 7890', email: 'sara.ali@revive.com' },
    { id: 'RV-00127', name: 'Omar Youssef', position: 'Trainer', level: 'Senior', gym: 'Nasr City', status: 'Active', initials: 'OY', hireDate: '2025-06-10', salary: 13000, phone: '+20 103 567 8901', email: 'omar.youssef@revive.com' },
    { id: 'RV-00128', name: 'Nour Ibrahim', position: 'Cleaner', level: 'Junior', gym: 'Nasr City', status: 'Active', initials: 'NI', hireDate: '2026-02-20', salary: 5000, phone: '+20 104 678 9012', email: 'nour.ibrahim@revive.com' },
    { id: 'RV-00129', name: 'Yasmin Adel', position: 'Trainer', level: 'Mid', gym: 'Heliopolis', status: 'On Leave', initials: 'YA', hireDate: '2025-11-01', salary: 11000, phone: '+20 105 789 0123', email: 'yasmin.adel@revive.com' },
    { id: 'RV-00130', name: 'Tarek Nabil', position: 'Receptionist', level: 'Junior', gym: 'Heliopolis', status: 'Active', initials: 'TN', hireDate: '2026-04-15', salary: 7500, phone: '+20 106 890 1234', email: 'tarek.nabil@revive.com' },
    { id: 'RV-00131', name: 'Mona Said', position: 'Trainer', level: 'Senior', gym: 'Heliopolis', status: 'Notice Period', initials: 'MS', hireDate: '2024-09-01', salary: 14000, phone: '+20 107 901 2345', email: 'mona.said@revive.com' },
    { id: 'RV-00132', name: 'Hassan Ali', position: 'Maintenance', level: 'Junior', gym: '6th October', status: 'Active', initials: 'HA', hireDate: '2026-01-05', salary: 6000, phone: '+20 108 012 3456', email: 'hassan.ali@revive.com' },
    { id: 'RV-00133', name: 'Fatma Hassan', position: 'Trainer', level: 'Mid', gym: '6th October', status: 'Active', initials: 'FH', hireDate: '2025-07-20', salary: 10500, phone: '+20 109 123 4567', email: 'fatma.hassan@revive.com' },
    { id: 'RV-00134', name: 'Ahmed Zaki', position: 'Trainer', level: 'Junior', gym: 'Nasr City', status: 'Active', initials: 'AZ', hireDate: '2026-06-01', salary: 8000, phone: '+20 110 234 5678', email: 'ahmed.zaki@revive.com' },
    { id: 'RV-00135', name: 'Laila Mostafa', position: 'Receptionist', level: 'Senior', gym: '6th October', status: 'Suspended', initials: 'LM', hireDate: '2025-03-10', salary: 9000, phone: '+20 111 345 6789', email: 'laila.mostafa@revive.com' },
    { id: 'RV-00136', name: 'Youssef Kamal', position: 'Branch Manager', level: 'Manager', gym: 'Nasr City', status: 'Active', initials: 'YK', hireDate: '2024-06-01', salary: 18000, phone: '+20 112 456 7890', email: 'youssef.kamal@revive.com' },
    { id: 'RV-00137', name: 'Hana Mostafa', position: 'Trainer', level: 'Senior', gym: 'Heliopolis', status: 'Active', initials: 'HM', hireDate: '2025-02-15', salary: 12500, phone: '+20 113 567 8901', email: 'hana.mostafa@revive.com' },
  ],
  attendanceRecords: [
    { employeeId: 'RV-00124', name: 'Ahmed Mohamed', gym: 'Nasr City', date: '2026-09-09', shift: '08:00–16:00', checkIn: '08:02', checkOut: null, status: 'On Time', source: 'Biometric' },
    { employeeId: 'RV-00125', name: 'Karim Hassan', gym: 'Nasr City', date: '2026-09-09', shift: '08:00–16:00', checkIn: '08:18', checkOut: null, status: 'Late', source: 'Biometric' },
    { employeeId: 'RV-00126', name: 'Sara Ali', gym: 'Nasr City', date: '2026-09-09', shift: '08:00–16:00', checkIn: '07:55', checkOut: null, status: 'On Time', source: 'Biometric' },
    { employeeId: 'RV-00127', name: 'Omar Youssef', gym: 'Nasr City', date: '2026-09-09', shift: '16:00–00:00', checkIn: null, checkOut: null, status: 'Off', source: '' },
    { employeeId: 'RV-00128', name: 'Nour Ibrahim', gym: 'Nasr City', date: '2026-09-09', shift: '08:00–16:00', checkIn: '06:00', checkOut: null, status: 'On Time', source: 'Biometric' },
    { employeeId: 'RV-00129', name: 'Yasmin Adel', gym: 'Heliopolis', date: '2026-09-09', shift: 'OFF', checkIn: null, checkOut: null, status: 'Absent', source: '', notes: 'On Leave' },
    { employeeId: 'RV-00134', name: 'Ahmed Zaki', gym: 'Nasr City', date: '2026-09-09', shift: '08:00–16:00', checkIn: '07:45', checkOut: null, status: 'On Time', source: 'Biometric' },
  ],
  shiftTemplates: [
    { id: 'st-morning', name: 'Morning', start: '08:00', end: '16:00', color: '#2563eb', bgColor: '#dbeafe', textColor: '#1e40af', isOff: false },
    { id: 'st-evening', name: 'Evening', start: '16:00', end: '00:00', color: '#006c49', bgColor: '#d1fae5', textColor: '#00422b', isOff: false },
    { id: 'st-night', name: 'Night', start: '00:00', end: '08:00', color: '#7c3aed', bgColor: '#ede9fe', textColor: '#5b21b6', isOff: false },
    { id: 'st-off', name: 'Off Day', start: null, end: null, color: '#6b7280', bgColor: '#f3f4f6', textColor: '#6b7280', isOff: true },
  ],
  scheduleCycles: [
    { id: 'c1', label: 'Aug 4 – Aug 13', status: 'Published' },
    { id: 'c2', label: 'Aug 14 – Aug 23', status: 'Published' },
    { id: 'c3', label: 'Aug 24 – Sep 2', status: 'Published' },
    { id: 'c4', label: 'Sep 3 – Sep 12', status: 'Draft' },
  ],
  teamSchedule: {
    't1': ['st-morning','st-evening','st-off','st-morning','st-evening','st-morning','st-off'],
    't2': ['st-morning','st-morning','st-evening','st-off','st-morning','st-morning','st-off'],
    't3': ['st-evening','st-off','st-morning','st-morning','st-evening','st-off','st-morning'],
    't4': ['st-morning','st-morning','st-morning','st-morning','st-morning','st-off','st-off'],
    't5': ['st-off','st-morning','st-evening','st-evening','st-off','st-morning','st-morning'],
    't6': ['st-evening','st-evening','st-off','st-morning','st-evening','st-evening','st-off'],
    't7': ['st-morning','st-off','st-morning','st-evening','st-morning','st-off','st-evening'],
    't8': ['st-morning','st-morning','st-off','st-morning','st-off','st-morning','st-morning'],
    't9': ['st-evening','st-morning','st-off','st-evening','st-evening','st-morning','st-off'],
    't10': ['st-morning','st-evening','st-morning','st-off','st-morning','st-evening','st-morning'],
  },
  todayIndex: 1,
  now: '14:30',
  teamMembers: [
    { id: 't1', name: 'Karim Hassan', position: 'Trainer', gym: 'Nasr City', status: 'Present', checkIn: '08:18', initials: 'KH' },
    { id: 't2', name: 'Sara Ali', position: 'Receptionist', gym: 'Nasr City', status: 'Present', checkIn: '07:55', initials: 'SA' },
    { id: 't3', name: 'Omar Youssef', position: 'Trainer', gym: 'Nasr City', status: 'Late', checkIn: '08:15', initials: 'OY' },
    { id: 't4', name: 'Nour Ibrahim', position: 'Cleaner', gym: 'Nasr City', status: 'Present', checkIn: '06:00', initials: 'NI' },
    { id: 't5', name: 'Yasmin Adel', position: 'Trainer', gym: 'Heliopolis', status: 'Absent', checkIn: null, initials: 'YA' },
    { id: 't6', name: 'Tarek Nabil', position: 'Receptionist', gym: 'Heliopolis', status: 'Present', checkIn: '15:52', initials: 'TN' },
    { id: 't7', name: 'Mona Said', position: 'Trainer', gym: 'Heliopolis', status: 'Present', checkIn: '07:50', initials: 'MS' },
    { id: 't8', name: 'Hassan Ali', position: 'Maintenance', gym: '6th October', status: 'Present', checkIn: '08:00', initials: 'HA' },
    { id: 't9', name: 'Fatma Hassan', position: 'Trainer', gym: '6th October', status: 'Late', checkIn: '08:20', initials: 'FH' },
    { id: 't10', name: 'Ahmed Zaki', position: 'Trainer', gym: 'Nasr City', status: 'Present', checkIn: '07:45', initials: 'AZ' },
  ],
  requests: [
    { id: 'r1', employee: 'Karim Hassan', gym: 'Nasr City', type: 'Day Off', submittedDate: '2026-09-07', requestedDate: 'Sep 12, 2026', status: 'Pending HR Review', bmDecision: 'Approved', bmComment: 'No scheduling conflict.', reason: 'Family event', timeline: [{ step: 'Submitted', date: 'Sep 7, 09:42 AM', done: true },{ step: 'BM Approved', date: 'Sep 7, 11:00 AM', done: true },{ step: 'HR Review', date: 'Pending', done: false }] },
    { id: 'r2', employee: 'Sara Ali', gym: 'Nasr City', type: 'Late Arrival', submittedDate: '2026-09-06', requestedDate: 'Sep 8, 2026', status: 'Approved', bmDecision: 'Approved', bmComment: 'Approved.', reason: 'Medical appointment', timeline: [{ step: 'Submitted', date: 'Sep 6, 08:15 AM', done: true },{ step: 'BM Approved', date: 'Sep 6, 09:00 AM', done: true },{ step: 'HR Approved', date: 'Sep 6, 10:00 AM', done: true }] },
    { id: 'r3', employee: 'Nour Ibrahim', gym: 'Nasr City', type: 'Day Off', submittedDate: '2026-09-05', requestedDate: 'Sep 15, 2026', status: 'Pending HR Review', bmDecision: 'Rejected', bmComment: 'High shortage on Sep 15.', reason: 'Personal errand', timeline: [{ step: 'Submitted', date: 'Sep 5, 02:30 PM', done: true },{ step: 'BM Rejected', date: 'Sep 5, 04:00 PM', done: true },{ step: 'HR Review', date: 'Pending', done: false }] },
    { id: 'r4', employee: 'Omar Youssef', gym: 'Nasr City', type: 'Shift Swap', submittedDate: '2026-09-04', requestedDate: 'Sep 10, 2026', status: 'Approved', bmDecision: 'Approved', bmComment: 'Swap with Karim confirmed.', reason: 'Need evening shift on Sep 10', timeline: [{ step: 'Submitted', date: 'Sep 4, 04:10 PM', done: true },{ step: 'BM Approved', date: 'Sep 5, 09:00 AM', done: true },{ step: 'HR Approved', date: 'Sep 5, 11:30 AM', done: true }] },
    { id: 'r5', employee: 'Fatma Hassan', gym: '6th October', type: 'Leave Early', submittedDate: '2026-09-08', requestedDate: 'Sep 9, 2026', status: 'Pending HR Review', bmDecision: 'Approved', bmComment: 'Handover to Hassan complete.', reason: 'Child sick', timeline: [{ step: 'Submitted', date: 'Sep 8, 11:15 AM', done: true },{ step: 'BM Approved', date: 'Sep 8, 02:30 PM', done: true },{ step: 'HR Review', date: 'Pending', done: false }] },
    { id: 'r6', employee: 'Tarek Nabil', gym: 'Heliopolis', type: 'Day Off', submittedDate: '2026-09-03', requestedDate: 'Sep 20, 2026', status: 'Approved', bmDecision: 'Approved', bmComment: 'Approved.', reason: 'Wedding anniversary', timeline: [{ step: 'Submitted', date: 'Sep 3, 10:00 AM', done: true },{ step: 'BM Approved', date: 'Sep 3, 01:00 PM', done: true },{ step: 'HR Approved', date: 'Sep 4, 09:00 AM', done: true }] },
  ],
  vacancies: [
    { id: 'v1', position: 'Senior Trainer', gym: 'Nasr City', headcount: 1, urgency: 'High', status: 'Open', createdDate: '2026-08-20', candidates: 5 },
    { id: 'v2', position: 'Receptionist', gym: 'Heliopolis', headcount: 1, urgency: 'Medium', status: 'Open', createdDate: '2026-08-15', candidates: 3 },
    { id: 'v3', position: 'Cleaner', gym: '6th October', headcount: 2, urgency: 'Low', status: 'Draft', createdDate: '2026-08-10', candidates: 0 },
    { id: 'v4', position: 'Trainer', gym: 'Nasr City', headcount: 1, urgency: 'Medium', status: 'Closed', createdDate: '2026-07-01', candidates: 8 },
  ],
  candidates: [
    { id: 'c1', name: 'Mohamed Salah', position: 'Senior Trainer', stage: 'Interview', appliedDate: '2026-08-22', phone: '+20 120 111 2222', rating: 4 },
    { id: 'c2', name: 'Nada Khaled', position: 'Senior Trainer', stage: 'Screening', appliedDate: '2026-08-25', phone: '+20 121 222 3333', rating: 3 },
    { id: 'c3', name: 'Tamer Hosny', position: 'Senior Trainer', stage: 'Offer', appliedDate: '2026-08-18', phone: '+20 122 333 4444', rating: 5 },
    { id: 'c4', name: 'Salma Nagib', position: 'Receptionist', stage: 'Interview', appliedDate: '2026-08-20', phone: '+20 123 444 5555', rating: 4 },
    { id: 'c5', name: 'Amr Diab', position: 'Receptionist', stage: 'Applied', appliedDate: '2026-08-28', phone: '+20 124 555 6666', rating: 0 },
    { id: 'c6', name: 'Shereen Adel', position: 'Trainer', stage: 'Hired', appliedDate: '2026-08-10', phone: '+20 125 666 7777', rating: 5, hiredDate: '2026-09-01' },
    { id: 'c7', name: 'Mostafa Nabil', position: 'Cleaner', stage: 'Screening', appliedDate: '2026-09-06', phone: '+20 126 777 8888', rating: 3 },
    { id: 'c8', name: 'Heba Said', position: 'Trainer', stage: 'Screening', appliedDate: '2026-09-08', phone: '+20 127 888 9999', rating: 3 },
  ],
  vacancyRequests: [
    { id: 'vr1', position: 'Senior Trainer', gym: 'Nasr City', urgency: 'High', status: 'Pending', submittedBy: 'Youssef Kamal', submittedDate: '2026-08-10', reason: 'Replacing departing trainer.' },
    { id: 'vr2', position: 'Receptionist', gym: 'Heliopolis', urgency: 'Medium', status: 'Pending', submittedBy: 'Hana Mostafa', submittedDate: '2026-08-15', reason: 'Evening shift coverage needed.' },
  ],
  payrollItems: [
    { employeeId: 'RV-00124', name: 'Ahmed Mohamed', gym: 'Nasr City', position: 'Trainer', days: 22, overtime: 8, gross: 12000, deductions: 900, net: 11100, status: 'Draft' },
    { employeeId: 'RV-00125', name: 'Karim Hassan', gym: 'Nasr City', position: 'Trainer', days: 21, overtime: 12, gross: 10000, deductions: 1100, net: 8900, status: 'Draft' },
    { employeeId: 'RV-00126', name: 'Sara Ali', gym: 'Nasr City', position: 'Receptionist', days: 22, overtime: 0, gross: 7000, deductions: 600, net: 6400, status: 'Draft' },
    { employeeId: 'RV-00127', name: 'Omar Youssef', gym: 'Nasr City', position: 'Trainer', days: 22, overtime: 16, gross: 13000, deductions: 1200, net: 11800, status: 'Approved' },
    { employeeId: 'RV-00128', name: 'Nour Ibrahim', gym: 'Nasr City', position: 'Cleaner', days: 21, overtime: 4, gross: 5000, deductions: 400, net: 4600, status: 'Draft' },
    { employeeId: 'RV-00130', name: 'Tarek Nabil', gym: 'Heliopolis', position: 'Receptionist', days: 20, overtime: 6, gross: 7500, deductions: 750, net: 6750, status: 'Draft' },
    { employeeId: 'RV-00132', name: 'Hassan Ali', gym: '6th October', position: 'Maintenance', days: 22, overtime: 10, gross: 6000, deductions: 500, net: 5500, status: 'Approved' },
    { employeeId: 'RV-00133', name: 'Fatma Hassan', gym: '6th October', position: 'Trainer', days: 22, overtime: 14, gross: 10500, deductions: 1000, net: 9500, status: 'Locked' },
  ],
  evaluationHistory: [
    { id: 'eh1', employee: 'Ahmed Mohamed', form: 'Trainer Evaluation Q3 2026', period: 'Q3 2026', score: 82, status: 'Completed', notes: 'Strong member feedback. Recommend advanced certification.' },
    { id: 'eh2', employee: 'Karim Hassan', form: 'Trainer Evaluation Q3 2026', period: 'Q3 2026', score: 70, status: 'Completed', notes: 'Attendance needs attention. 3 late arrivals this month.' },
    { id: 'eh3', employee: 'Sara Ali', form: 'Receptionist Evaluation Q2 2026', period: 'Q2 2026', score: 88, status: 'Completed' },
    { id: 'eh4', employee: 'Omar Youssef', form: 'Trainer Evaluation Q3 2026', period: 'Q3 2026', score: 74, status: 'In Progress', notes: 'Punctuality issues flagged.' },
    { id: 'eh5', employee: 'Yasmin Adel', form: 'Probation Review', period: 'Q2 2026', score: 55, status: 'Completed', notes: 'On leave since June. Needs improvement plan.' },
  ],
  payroll: [
    { id: 'p1', period: 'August 2026', status: 'Processing', paidDate: null, totalEmployees: 138, totalGross: 1450000, totalDeductions: 180000, totalNet: 1270000, visible: false },
    { id: 'p2', period: 'July 2026', status: 'Paid', paidDate: '2026-08-05', totalEmployees: 140, totalGross: 1480000, totalDeductions: 185000, totalNet: 1295000, visible: true,
      items: [
        { employee: 'Ahmed Mohamed', position: 'Trainer', gym: 'Nasr City', gross: 13900, deductions: 1500, net: 12400 },
        { employee: 'Karim Hassan', position: 'Trainer', gym: 'Nasr City', gross: 10500, deductions: 1300, net: 9200 },
        { employee: 'Sara Ali', position: 'Receptionist', gym: 'Nasr City', gross: 7200, deductions: 900, net: 6300 },
        { employee: 'Omar Youssef', position: 'Trainer', gym: 'Nasr City', gross: 14200, deductions: 1600, net: 12600 },
        { employee: 'Nour Ibrahim', position: 'Cleaner', gym: 'Nasr City', gross: 5100, deductions: 600, net: 4500 },
      ],
    },
    { id: 'p3', period: 'June 2026', status: 'Paid', paidDate: '2026-07-05', totalEmployees: 139, totalGross: 1460000, totalDeductions: 182000, totalNet: 1278000, visible: true },
    { id: 'p4', period: 'May 2026', status: 'Paid', paidDate: '2026-06-05', totalEmployees: 138, totalGross: 1440000, totalDeductions: 178000, totalNet: 1262000, visible: true },
  ],
  evaluationForms: [
    { id: 'ef1', name: 'Trainer Evaluation Q3 2026', gym: 'All', position: 'Trainer', questions: 8, status: 'Active', createdDate: '2026-08-01' },
    { id: 'ef2', name: 'Receptionist Evaluation Q2 2026', gym: 'All', position: 'Receptionist', questions: 6, status: 'Completed', createdDate: '2026-05-01' },
    { id: 'ef3', name: 'Staff Onboarding Checklist', gym: 'All', position: 'All', questions: 12, status: 'Active', createdDate: '2026-01-01' },
  ],
  evaluations: [
    { id: 'e1', employee: 'Ahmed Mohamed', position: 'Trainer', period: 'Q2 2026', score: 4.2, result: 'Exceeds', status: 'Completed', gym: 'Nasr City' },
    { id: 'e2', employee: 'Karim Hassan', position: 'Trainer', period: 'Q2 2026', score: 3.8, result: 'Meets', status: 'Completed', gym: 'Nasr City' },
    { id: 'e3', employee: 'Sara Ali', position: 'Receptionist', period: 'Q2 2026', score: 4.0, result: 'Exceeds', status: 'Completed', gym: 'Nasr City' },
    { id: 'e4', employee: 'Omar Youssef', position: 'Trainer', period: 'Q2 2026', score: 3.1, result: 'Meets', status: 'Completed', gym: 'Nasr City' },
    { id: 'e5', employee: 'Yasmin Adel', position: 'Trainer', period: 'Q2 2026', score: 2.6, result: 'Below', status: 'Completed', gym: 'Heliopolis' },
    { id: 'e6', employee: 'Fatma Hassan', position: 'Trainer', period: 'Q2 2026', score: 4.5, result: 'Exceeds', status: 'Completed', gym: '6th October' },
  ],
  announcements: [
    { id: 'a1', title: 'Updated Attendance Policy', audience: 'All Employees', sentDate: '2026-09-01', status: 'Sent', readRate: 78 },
    { id: 'a2', title: 'Q3 Team Building Event', audience: 'All Employees', sentDate: '2026-08-25', status: 'Sent', readRate: 92 },
    { id: 'a3', title: 'New Dress Code Guidelines', audience: 'Nasr City', sentDate: '2026-08-15', status: 'Sent', readRate: 85 },
  ],
  positions: [
    { id: 'pos1', title: 'Trainer', levels: ['Junior','Mid','Senior'], department: 'Training', gym: 'All', headcount: 42, active: 38 },
    { id: 'pos2', title: 'Receptionist', levels: ['Junior','Senior'], department: 'Front Desk', gym: 'All', headcount: 12, active: 11 },
    { id: 'pos3', title: 'Cleaner', levels: ['Junior'], department: 'Facilities', gym: 'All', headcount: 15, active: 14 },
    { id: 'pos4', title: 'Maintenance', levels: ['Junior'], department: 'Facilities', gym: 'All', headcount: 8, active: 8 },
    { id: 'pos5', title: 'Branch Manager', levels: ['Manager'], department: 'Management', gym: 'All', headcount: 3, active: 3 },
  ],
  auditLog: [
    { id: 'al1', action: 'Employee Status Changed', user: 'Mona El-Sayed', target: 'Yasmin Adel', detail: 'Status changed to On Leave', timestamp: '2026-09-09 10:15', gym: 'Heliopolis' },
    { id: 'al2', action: 'Request Approved', user: 'Mona El-Sayed', target: 'Sara Ali', detail: 'Late Arrival request for Sep 8 approved', timestamp: '2026-09-06 10:00', gym: 'Nasr City' },
    { id: 'al3', action: 'Payroll Locked', user: 'Mona El-Sayed', target: 'July 2026', detail: 'Payroll run for July 2026 approved and locked', timestamp: '2026-08-05 14:30', gym: 'All' },
    { id: 'al4', action: 'Employee Created', user: 'Mona El-Sayed', target: 'Ahmed Zaki', detail: 'New employee onboarded — Trainer, Junior', timestamp: '2026-06-01 09:00', gym: 'Nasr City' },
    { id: 'al5', action: 'Vacancy Approved', user: 'Mona El-Sayed', target: 'Senior Trainer', detail: 'Vacancy request for Nasr City approved', timestamp: '2026-08-20 11:00', gym: 'Nasr City' },
    { id: 'al6', action: 'Evaluation Completed', user: 'Mona El-Sayed', target: 'Ahmed Mohamed', detail: 'Q2 2026 evaluation — Score: 4.2/5', timestamp: '2026-08-01 16:00', gym: 'Nasr City' },
    { id: 'al7', action: 'Bulk Import', user: 'Mona El-Sayed', target: '14 employees', detail: 'CSV import completed — 14 records added', timestamp: '2026-03-01 10:30', gym: 'All' },
  ],
  events: [
    { id: 'ev1', type: 'Document Expiry', title: 'First Aid Cert — Ahmed Mohamed', date: '2026-09-10', urgency: 'high', detail: 'Cert expires in 1 day' },
    { id: 'ev2', type: 'Contract Expiry', title: 'Contract — Mona Said', date: '2026-09-30', urgency: 'medium', detail: 'Contract expires in 21 days. Employee is on notice period.' },
    { id: 'ev3', type: 'PendingHRReview', title: 'Request — Karim Hassan (Day Off)', date: '2026-09-12', urgency: 'medium', detail: 'BM approved. Awaiting HR final decision.' },
    { id: 'ev4', type: 'PendingHRReview', title: 'Request — Fatma Hassan (Leave Early)', date: '2026-09-09', urgency: 'high', detail: 'BM approved. Request is for today.' },
    { id: 'ev5', type: 'PendingVacancyRequest', title: 'Vacancy Request — Senior Trainer', date: '2026-08-10', urgency: 'medium', detail: 'Branch Manager request pending HR approval.' },
    { id: 'ev6', type: 'Resignation', title: 'Mona Said — Notice Period', date: '2026-09-30', urgency: 'low', detail: 'Last day Sep 30. Exit checklist in progress.' },
  ],
  notifications: [
    { id: 'n1', category: 'Requests', title: 'New Request Pending', description: 'Karim Hassan submitted a Day Off request for Sep 12.', date: '2026-09-07 09:42', read: false, color: 'yellow', link: 'requests' },
    { id: 'n2', category: 'Requests', title: 'BM Approved Request', description: 'Fatma Hassan Leave Early request approved by Branch Manager.', date: '2026-09-08 14:30', read: false, color: 'green', link: 'requests' },
    { id: 'n3', category: 'Recruitment', title: 'New Candidate Applied', description: 'Amr Diab applied for Receptionist position at Heliopolis.', date: '2026-09-08 11:00', read: false, color: 'blue', link: 'recruitment' },
    { id: 'n4', category: 'Document', title: 'Document Expiring', description: 'Ahmed Mohamed First Aid Certification expires Sep 10.', date: '2026-09-09 08:00', read: false, color: 'red', link: 'events' },
    { id: 'n5', category: 'System', title: 'Payroll Processing', description: 'August 2026 payroll is being processed.', date: '2026-09-05 09:00', read: true, color: 'purple', link: 'payroll' },
    { id: 'n6', category: 'Announcements', title: 'Policy Acknowledged', description: '92% of staff acknowledged the Updated Attendance Policy.', date: '2026-09-03 16:00', read: true, color: 'green', link: 'notifications' },
  ],
  interviews: [
    { id: 'iv1', candidate: 'Mohamed Salah', position: 'Senior Trainer', gym: 'Nasr City', date: '2026-09-10', time: '11:00', type: 'Video', interviewer: 'Youssef Kamal', status: 'Scheduled', room: 'Meet — revive/salah' },
    { id: 'iv2', candidate: 'Salma Nagib', position: 'Receptionist', gym: 'Heliopolis', date: '2026-09-10', time: '13:30', type: 'On-site', interviewer: 'Hana Mostafa', status: 'Scheduled', room: 'Heliopolis HQ — Room 2' },
    { id: 'iv3', candidate: 'Tamer Hosny', position: 'Senior Trainer', gym: 'Nasr City', date: '2026-09-11', time: '10:00', type: 'On-site', interviewer: 'Omar Youssef', status: 'Scheduled', room: 'Nasr City — Office' },
    { id: 'iv4', candidate: 'Nada Khaled', position: 'Senior Trainer', gym: 'Nasr City', date: '2026-09-12', time: '12:00', type: 'Video', interviewer: 'Youssef Kamal', status: 'Invited', room: 'Meet — revive/nada' },
    { id: 'iv5', candidate: 'Amr Diab', position: 'Receptionist', gym: 'Heliopolis', date: '2026-09-15', time: '14:00', type: 'On-site', interviewer: 'Hana Mostafa', status: 'Draft', room: 'Heliopolis HQ — Room 2' },
  ],
  waitingList: [
    { id: 'wl1', name: 'Dina Farouk', position: 'Trainer', note: 'Strong candidate — no open vacancy at preferred gym yet.', since: '2026-08-30', source: 'Walk-in' },
    { id: 'wl2', name: 'Mahmoud Samir', position: 'Receptionist', note: 'Waiting for Heliopolis evening shift opening.', since: '2026-09-01', source: 'Referral — Hana' },
    { id: 'wl3', name: 'Rania Gomaa', position: 'Cleaner', note: 'Hold — headcount request under review.', since: '2026-09-05', source: 'LinkedIn' },
  ],
  newComers: [
    { id: 'nc1', name: 'Ahmed Zaki', position: 'Trainer — Junior', startDate: '2026-09-01', progress: 80, checklist: [['Contract signed', true], ['ID uploaded', true], ['Uniform issued', true], ['Bank account set', true], ['First Aid cert', false]] },
    { id: 'nc2', name: 'Nourhan Ali', position: 'Receptionist — Junior', startDate: '2026-09-07', progress: 50, checklist: [['Contract signed', true], ['ID uploaded', true], ['Uniform issued', false], ['Bank account set', false], ['First Aid cert', false]] },
    { id: 'nc3', name: 'Seif El-Din', position: 'Maintenance — Junior', startDate: '2026-09-14', progress: 20, checklist: [['Contract signed', true], ['ID uploaded', false], ['Uniform issued', false], ['Bank account set', false], ['First Aid cert', false]] },
  ],
  separations: [
    { id: 'sep1', employee: 'Mona Said', position: 'Trainer — Senior', gym: 'Heliopolis', lastDay: '2026-09-30', reason: 'Resignation — relocating', status: 'Notice Period', progress: 45, checklist: [['Exit interview scheduled', true], ['Handover completed', true], ['Uniform returned', false], ['Access cards revoked', false], ['Final settlement', false]] },
    { id: 'sep2', employee: 'Yasmin Adel', position: 'Trainer — Mid', gym: 'Heliopolis', lastDay: '2026-09-20', reason: 'Contract non-renewal', status: 'In Progress', progress: 70, checklist: [['Exit interview scheduled', true], ['Handover completed', true], ['Uniform returned', true], ['Access cards revoked', false], ['Final settlement', false]] },
    { id: 'sep3', employee: 'Laila Mostafa', position: 'Receptionist — Senior', gym: '6th October', lastDay: '2026-09-25', reason: 'Termination — repeated tardiness', status: 'In Review', progress: 20, checklist: [['Exit interview scheduled', false], ['Handover completed', false], ['Uniform returned', false], ['Access cards revoked', false], ['Final settlement', false]] },
  ],
  goals: [
    { id: 'g1', employee: 'Ahmed Mohamed', title: 'Certify as Advanced Trainer', status: 'On Track', progress: 75, due: '2026-12-31', owner: 'Self' },
    { id: 'g2', employee: 'Karim Hassan', title: 'Zero late arrivals in October', status: 'At Risk', progress: 40, due: '2026-10-31', owner: 'Mona El-Sayed' },
    { id: 'g3', employee: 'Sara Ali', title: 'Lead reception onboarding for new hire', status: 'On Track', progress: 60, due: '2026-11-30', owner: 'Hana Mostafa' },
    { id: 'g4', employee: 'Omar Youssef', title: 'Reduce client complaints by 20%', status: 'Behind', progress: 30, due: '2026-12-31', owner: 'Youssef Kamal' },
  ],
  performanceCycles: [
    { id: 'pc1', name: 'Q1 2026 Review', start: '2026-01-05', end: '2026-01-31', status: 'Completed' },
    { id: 'pc2', name: 'Mid-Year Review', start: '2026-07-01', end: '2026-07-31', status: 'Completed' },
    { id: 'pc3', name: 'Q3 2026 Review', start: '2026-10-01', end: '2026-10-31', status: 'Upcoming' },
  ],
  permissionMatrix: {
    depts: ['Employees', 'Attendance', 'Schedule', 'Requests', 'Recruitment', 'Payroll', 'Evaluations'],
    roles: [
      { name: 'HR Manager', perms: { Employees: 9, Attendance: 3, Schedule: 3, Requests: 3, Recruitment: 3, Payroll: 3, Evaluations: 3 } },
      { name: 'HR Specialist', perms: { Employees: 6, Attendance: 2, Schedule: 3, Requests: 2, Recruitment: 2, Payroll: 1, Evaluations: 2 } },
      { name: 'Branch Manager', perms: { Employees: 3, Attendance: 1, Schedule: 1, Requests: 2, Recruitment: 1, Payroll: 0, Evaluations: 1 } },
    ],
  },
  settings: { emailNotifications: true, pushNotifications: true },
};

// ==================== DEMO USERS ====================
const DEMO_USERS = {
  hrManager: {
    id: 'RV-00102', firstName: 'Mona', lastName: 'El-Sayed', fullName: 'Mona El-Sayed',
    email: 'mona.elsayed@revive.com', phone: '+20 103 456 7890', initials: 'ME',
    position: 'HR Manager', level: 'Manager',
    gyms: [
      { id: 'gym-1', name: 'Revive Gym', branch: 'Nasr City' },
      { id: 'gym-2', name: 'Revive Gym', branch: 'Heliopolis' },
      { id: 'gym-3', name: 'Revive Fitness', branch: '6th October' },
    ],
    selectedGym: 'all',
    hireDate: '2024-03-15', employmentType: 'Full-time', status: 'Active',
    role: 'HR Manager',
    permissions: ['employees.view','employees.create','employees.edit','employees.transfer','employees.position.change','employees.role.assign','employees.status.change','employees.compensation.manage','employees.contract.manage','employees.offboard','employees.documents.view','employees.documents.manage','employees.bulk_import','employees.leave_balance.manage','positions.view','positions.manage','attendance.view','attendance.edit','attendance.manual_entry','schedule.view','schedule.manage','requests.view','requests.approve','payroll.view','payroll.edit','payroll.approve','evaluations.view','evaluations.manage','reports.view','announcements.view','announcements.manage','audit.view','team.view','team.manage','recruitment.view','recruitment.vacancies.manage','recruitment.candidates.manage','recruitment.hire.approve','recruitment.vacancy_request.approve'],
  },
  hr: {
    id: 'RV-00201', firstName: 'Sarah', lastName: 'Hassan', fullName: 'Sarah Hassan',
    email: 'sarah.hassan@revive.com', phone: '+20 102 345 6789', initials: 'SH',
    position: 'HR Specialist', level: 'Senior',
    gyms: [
      { id: 'gym-1', name: 'Revive Gym', branch: 'Nasr City' },
      { id: 'gym-2', name: 'Revive Gym', branch: 'Heliopolis' },
    ],
    selectedGym: 'all',
    hireDate: '2025-06-01', employmentType: 'Full-time', status: 'Active',
    role: 'HR',
    permissions: ['employees.view','employees.create','employees.edit','employees.position.change','employees.status.change','employees.contract.manage','employees.documents.view','employees.documents.manage','positions.view','attendance.view','attendance.edit','schedule.view','schedule.manage','requests.view','requests.approve','payroll.view','recruitment.view','recruitment.candidates.manage','evaluations.view','announcements.view','team.view'],
  },
};
