services:
  - type: web
    name: revive-hr-biometrics
    runtime: docker
    dockerfilePath: ./hf_biometric_space/Dockerfile
    dockerContext: ./hf_biometric_space
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 7860
